import {
  Box,
  Container,
  css,
  Flex,
  Heading,
  Image,
  Text,
} from "@chakra-ui/react";
import ChakraUIRenderer from "chakra-ui-markdown-renderer";
import { NextPage } from "next";
import Head from "next/head";
import Highlight from "react-highlight";
import ReactMarkdown from "react-markdown";
import { infra } from "../../infra";
import theme from "../../theme";
import sizes from "../../theme/foundations/sizes";
import "/node_modules/highlight.js/styles/gruvbox-dark.css";

interface Params {
  post: {
    fields?: any;
  };
}
const regexp = new RegExp(/(\r\n|\n|\r)/gm);

const newTheme = {
  code: (props) => {
    const { children } = props;

    if (regexp.test(children[0])) {
      return (
        <Flex
          display={"inline-block"}
          maxWidth={"4xl"}
          // marginLeft={`calc((-${sizes["4xl"]} + ${sizes["2xl"]}) / 2)`}
          // marginRight={`calc((-${sizes["4xl"]} + ${sizes["2xl"]}) / 2)`}
          // paddingLeft={`calc((-${sizes["4xl"]} + ${sizes["2xl"]}) / 2)`}
          // paddingRight={`calc((-${sizes["4xl"]} + ${sizes["2xl"]}) / 2)`}
          py={4}
          justifyContent={"center"}
          flexDirection={"column"}
        >
          <Highlight>{children}</Highlight>
        </Flex>
      );
    }
    return (
      <Box display={"inline-flex"}>
        <Highlight>{children}</Highlight>
      </Box>
    );
  },
};

const BlogPage: NextPage<Params> = (props) => {
  console.log(props);
  return (
    <Box bgColor={"quinary"} height={"100%"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box
          bgColor={"primary"}
          width={"100%"}
          color={"quinary"}
          paddingBottom={2}
        >
          <Container>
            <Flex
              alignItems={"center"}
              flexDirection={"column"}
              marginBottom={8}
            >
              <Heading as="h1" fontSize={{ base: "4xl", md: "6xl" }}>
                {props.post?.fields?.title}
              </Heading>
              <Text fontSize={"2xl"}>
                {new Date(props.post?.fields?.publishDate).toLocaleDateString()}
              </Text>
            </Flex>
          </Container>
          <Container maxW={"4xl"}>
            {props.post?.fields?.heroImage?.fields?.file?.url && (
              <Image
                src={`https:${props.post?.fields?.heroImage?.fields?.file?.url}`}
                alt={props.post?.fields?.imageAlt}
                width={"100%"}
                height={"auto"}
                paddingBottom={4}
              />
            )}
          </Container>
          <Container maxW={"2xl"}>
            <Text fontSize={"2xl"} marginBottom={6}>
              {props.post?.fields?.description}
            </Text>
          </Container>
        </Box>
        <Box width={"100%"} paddingBottom={2}>
          <Container maxW={"2xl"}>
            <Box fontSize={"xl"}>
              <ReactMarkdown components={ChakraUIRenderer(newTheme)} skipHtml>
                {props.post?.fields?.body}
              </ReactMarkdown>
            </Box>
          </Container>
        </Box>
      </main>
    </Box>
  );
};

export async function getStaticProps(context: any) {
  const item = await infra.api.posts.getEntryBySlug(context.params.slug);

  return {
    props: {
      post: item,
    },
    revalidate: 10000,
  };
}

export async function getStaticPaths() {
  const paths = await infra.api.posts.getPostPaths();

  return { paths, fallback: true };
}

export default BlogPage;
