import {
  Box,
  chakra,
  Container,
  Flex,
  Heading,
  Icon,
  Link,
  Text,
} from "@chakra-ui/react";
import { ArrowNarrowRightIcon } from "@heroicons/react/solid";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { ArticleList } from "../../components/ArticleList";
import { infra } from "../../infra";
interface Props {
  articles: any[];
}

const Index: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <chakra.main bgColor={"quinary.500"}>
        <Flex
          background={"primary.500"}
          paddingTop={8}
          paddingBottom={8}
          flexDirection={"column"}
        >
          <Container maxW={"7xl"} display={"flex"} flexDirection={"column"}>
            <Heading
              mb={6}
              fontSize={{ base: "4xl", md: "6xl" }}
              fontWeight="bold"
              lineHeight="none"
              letterSpacing={"wide"}
              color={"quinary.500"}
            >
              Posts
            </Heading>
            <Text
              fontSize={"2xl"}
              marginBottom={6}
              maxW={"xl"}
              right={0}
              justifySelf={"flex-end"}
              alignSelf={"flex-end"}
              color={"quinary.500"}
            >
              I like to write about things that I learned in the field as a
              software developer. In these posts I will generally ramble on
              about the latest technolgies, paradigms and random developer
              related topics.
            </Text>
            <ArticleList articles={props.articles}></ArticleList>
          </Container>
        </Flex>
      </chakra.main>
    </>
  );
};

export async function getStaticProps() {
  const result = await infra.api.posts.getEntries();

  return {
    props: {
      articles: result.items ?? null,
    },
    revalidate: 1,
  };
}

export default Index;
