import { useColorModeValue } from "@chakra-ui/color-mode";
import {
  Box,
  chakra,
  Container,
  Flex,
  Heading,
  Icon,
  Text,
  Link,
} from "@chakra-ui/react";
import NextLink from "next/link";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { ArticleList } from "../components/ArticleList";
import { Hero } from "../components/Hero";
import { infra } from "../infra";
import styles from "../styles/Home.module.css";
import { ArrowNarrowRightIcon } from "@heroicons/react/solid";
import { FeaturedWork } from "../components/FeaturedWork/FeaturedWork";
interface Props {
  articles: any[];
  works: any[];
}

const Home: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <chakra.main>
        <Container maxW={"7xl"} overflow={"visible"}>
          <Hero />
        </Container>
        <Box
          position={"relative"}
          background={"primary"}
          paddingTop={16}
          paddingBottom={16}
        >
          <Container maxW={"7xl"} display={"flex"} flexDirection={"column"}>
            <Heading as="h2" marginBottom={8} color="quinary" fontSize={"5xl"}>
              Featured posts
            </Heading>
            <Text
              fontSize={"2xl"}
              marginBottom={16}
              maxW={"xl"}
              right={0}
              justifySelf={"flex-end"}
              alignSelf={"flex-end"}
              color={"quinary"}
            >
              I write about topics that I learned in the field as a software
              developer. In my posts I will generally ramble on about the latest
              technolgies, paradigms or I just like to vent my heart about
              something.
            </Text>
            <ArticleList articles={props.articles}></ArticleList>
            <Flex width={"100%"} justifyContent={"flex-end"} marginTop={2}>
              <NextLink href="/posts" passHref>
                <Link fontSize={"3xl"}>
                  See all posts{" "}
                  <Icon>
                    <ArrowNarrowRightIcon />
                  </Icon>{" "}
                </Link>
              </NextLink>
            </Flex>
          </Container>
        </Box>
      </chakra.main>
    </>
  );
};

export async function getStaticProps() {
  const postResult = await infra.api.posts.getEntries();
  const workResult = await infra.api.works.getEntries();

  return {
    props: {
      articles: postResult.items ?? null,
      works: workResult.items ?? null,
    },
    revalidate: 1,
  };
}

export default Home;
